spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  spring:
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
  server:
    port: 8080