spring:
  application:
    name: auth



  jwt:
    header: Authorization
    secret: $2a$12$NXV0v0iY0.i/a80cTLOh2O7bWa8yBL4ipwnp9mwDvfHK6z2gaeyqi
    access-token-validity-in-seconds: 86400  # 1 day
    refresh-token-validity-in-seconds: 604800  # 7 days


redis:
  master:
    host: http://J10a205.p.ssafy.io
    port: 6379
#  nodes:
#    - host: something
#      port: 6379
#    - host: something2
#      port: 6379
  password: godqhraksEkd123@@



server:
  port: 8000


logging:
  level:
    root: debug